controller:
  hostNetwork: true
  hostPort:
    enabled: true
  replicaCount: 2
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"

