controller:
  replicaCount: 2
  service:
    type: LoadBalancer
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  config:
    use-forwarded-headers: "true"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      scrapeInterval: 30s
      additionalLabels:
        release: prometheus
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "nginx_ingress_controller_requests.*"
          action: keep
