ingress:
  enabled: true
  hosts:
    - grafana.dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - grafana.dev
      secretName: grafana-tls
