#replicaCount: 1
#
#image:
#  repository: grafana/grafana
#  tag: "11.5.2"
#  pullPolicy: IfNotPresent
#
#service:
#  type: ClusterIP
#  port: 80
#
#ingress:
#  enabled: false
#
#resources:
#  limits:
#    cpu: 200m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
#
#persistence:
#  enabled: false
#  accessModes:
#    - ReadWriteOnce
#  size: 10Gi
#
#adminUser: admin
#adminPassword: "changeme"
#
#serviceAccount:
#  create: true
#  name: grafana
#
#datasources:
#  datasources.yaml:
#    apiVersion: 1
#    datasources:
#      - name: Prometheus
#        type: prometheus
#        access: proxy
#        url: http://prometheus-server.monitoring.svc.cluster.local:80
#        isDefault: true
#
#dashboardProviders:
#  dashboardproviders.yaml:
#    apiVersion: 1
#    providers:
#      - name: 'default'
#        orgId: 1
#        folder: ''
#        type: file
#        disableDeletion: false
#        editable: true
#        options:
#          path: /var/lib/grafana/dashboards/default
#
#dashboards:
#  default:
#    example-dashboard:
#      json: |
#        {
#          "annotations": {
#            "list": []
#          },
#          "panels": [],
#          "schemaVersion": 30,
#          "title": "Example Dashboard",
#          "version": 1
#        }