apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-alerts
  namespace: monitoring
  labels:
    release: prometheus
    app: prometheus
spec:
  groups:
    - name: kubernetes-rules
      rules:
        - alert: KubernetesEtcdHighLatency
          expr: histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) > 0.1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Etcd High Latency"
            description: "Etcd WAL sync latency is above 100ms for 5 minutes."
        - alert: NodeCPUHigh
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Node CPU High Usage"
            description: "CPU usage on a node is above 85% for 10 minutes."
