apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ingress-nginx-alerts
  namespace: monitoring
  labels:
    release: prometheus
    app: prometheus
spec:
  groups:
    - name: ingress-nginx-rules
      rules:
        - alert: HighIngress5xxErrors
          expr: rate(nginx_ingress_controller_requests{status=~"5.*"}[5m]) > 10
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Ingress high 5xx errors"
            description: "Ingress Nginx returns more than 10 5xx errors per second for 2 minutes."
