persistence:
  enabled: true
  size: 10Gi

adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - grafana.dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - grafana.dev
      secretName: grafana-tls

serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 30s
  scrapeTimeout: 10s
  path: /metrics
  scheme: http
  labels:
    release: prometheus
  targetLabels:
    - instance
  metricRelabelings:
    - sourceLabels: [__name__]
      regex: "go.*"
      action: keep


datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.default.svc:9090
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes:
      gnetId: 315
      revision: 1
      datasource: Prometheus
    nodes:
      gnetId: 1860
      revision: 1
      datasource: Prometheus
    api-server:
      gnetId: 1621
      revision: 1
      datasource: Prometheus
    kubelet:
      gnetId: 1766
      revision: 1
      datasource: Prometheus
    etcd:
      gnetId: 3070
      revision: 1
      datasource: Prometheus
    core-dns:
      gnetId: 3662
      revision: 1
      datasource: Prometheus

