apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auto-discovery
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
